### ISSUE TITLE
license missing - can we reuse the code?

### ISSUE THREAD

**Issue by nblumoe** [martinklepsch/fun-club#1]
Hey Martin,

there is no license on this project. Would you mind adding one?
I need to confess to already have reused it over here:
https://github.com/PVA-Parrot/PVA-Parrot

This project of mine could develop into a commercial application. A liberal license on this repository here would be great to allow me keep using it as an application skeleton.

Would be awesome and highly appreciated, thanks! :)

**Comment by martinklepsch** [comment]
EPL World for you?. PR adding License file welcome!

On Thursday, February 26, 2015, Nils Blum-Oeste notifications@github.com
wrote:

> Hey Martin,
> 
> there is no license on this project. Would you mind adding one?
> I need to confess to already have reused it over here:
> https://github.com/PVA-Parrot/PVA-Parrot
> 
> This project of mine could develop into a commercial application. A
> liberal license on this repository here would be great to allow me keep
> using it as an application skeleton.
> 
> Would be awesome and highly appreciated, thanks! :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/martinklepsch/fun-club/issues/1.

## 

—
Martin
http://martinklepsch.org http://martinklepsch.org?ref=email

**Comment by martinklepsch** [comment]
*works

On Thursday, February 26, 2015, Martin Klepsch martinklepsch@googlemail.com
wrote:

> EPL World for you?. PR adding License file welcome!
> 
> On Thursday, February 26, 2015, Nils Blum-Oeste <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > Hey Martin,
> > 
> > there is no license on this project. Would you mind adding one?
> > I need to confess to already have reused it over here:
> > https://github.com/PVA-Parrot/PVA-Parrot
> > 
> > This project of mine could develop into a commercial application. A
> > liberal license on this repository here would be great to allow me keep
> > using it as an application skeleton.
> > 
> > Would be awesome and highly appreciated, thanks! :)
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/martinklepsch/fun-club/issues/1.
> 
> ## 
> 
> —
> Martin
> http://martinklepsch.org http://martinklepsch.org?ref=email

## 

—
Martin
http://martinklepsch.org http://martinklepsch.org?ref=email

**Comment by nblumoe** [comment]
Sure EPL is fine. My project is going to use AGPL

**Comment by nblumoe** [comment]
Thanks a lot! :+1:
